#!/usr/bin/ruby
txmt_param = ARGV[0] 
xmt_path = txmt_param.match("%2F.*&").to_s  	
txmt_path = txmt_path [0...-1] 						
txmt_path_slashed = txmt_path.gsub("%2F","/") 	
txmt_line = txmt_param.match("&line=.*").to_s 	
txmt_line = txmt_line [6..txmt_line.length] 		
vim_params = Array.new 
vim_params = "--remote-tab-silent"
vim_params << " +#{txmt_line}" if txmt_line
vim_params << " #{txmt_path_slashed}"

`gvim  #{vim_params}`
